<?php

/**
 * Reading Progress Bar Plugin
 *
 * Plugin Name:       Reading Progress Bar
 * Plugin URI:        https://github.com/pradeepvegeta/reading-progress-bar-react
 * Description:       Display a progress bar indicating reading progress on the frontend.
 * Version:           1.0.0
 * Requires at least: 6.8
 * Requires PHP:      8.0
 * Author:            Pradeep Kumar
 * Author URI:        https://github.com/pradeepvegeta/
 * License:           GPL v2 or later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Update URI:        https://example.com/my-plugin/
 * Text Domain:       reading-progress-bar
 *
 * @package           Reading_Progress_Bar
 * @since             1.0.0
 */

declare(strict_types=1);

namespace Reading_Progress_Bar;

if (! defined('ABSPATH')) {
    exit;
}

if (file_exists(plugin_dir_path(__FILE__) . 'vendor/autoload.php')) {
    require_once plugin_dir_path(__FILE__) . 'vendor/autoload.php';
} else {
    wp_trigger_error(
        __FUNCTION__,
        'Reading Progress Bar Plugin: Composer autoload file not found. Please run `composer install`.',
        E_USER_ERROR
    );
    return;
}

/**
 * Main Reading Progress Bar Plugin Class
 *
 * Handles plugin initialization, settings page registration, and script/style enqueuing.
 *
 * @class Reading_Progress_Bar
 * @since 1.0.0
 */
class Reading_Progress_Bar
{
    /**
     * Constructor
     *
     * Initializes plugin hooks and actions.
     *
     * @since 1.0.0
     */
    public function __construct()
    {
        // Register the settings page under Settings > Reading Progress Bar.
        add_action('admin_menu', [$this, 'reading_progress_bar_settings_page']);

        // Enqueue the compiled React bundle only on the plugin's admin settings page.
        add_action('admin_enqueue_scripts', [$this, 'reading_progress_bar_settings_page_enqueue_script']);

        // Enqueue the progress bar CSS on every frontend page; the bar is only
        // rendered via wp_body_open when the post type matches, but the CSS must
        // be loaded unconditionally so the scroll-timeline animation is available.
        add_action('wp_enqueue_scripts', [$this, 'reading_progress_bar_enqueue_style']);

        // Register the option with the REST API so the React settings page can
        // read and write it via /wp/v2/settings.
        add_action('init', [$this, 'reading_progress_bar_settings']);

        // Output the progress bar <div> immediately after <body> opens on the frontend.
        add_action('wp_body_open', [$this, 'reading_progress_bar_front_page']);

        // Delete the option field value when deactivating the plugin
        register_deactivation_hook(__FILE__, [$this, 'delete_reading_progress_bar_option']);
    }

    /**
     * Register Settings Page
     *
     * Adds the plugin settings page to the WordPress admin menu.
     *
     * @since 1.0.0
     */
    public function reading_progress_bar_settings_page()
    {
        add_options_page(
            __('Reading Progress Bar', 'reading-progress-bar'),
            __('Reading Progress Bar', 'reading-progress-bar'),
            'manage_options',
            'reading-progress-bar',
            [$this, 'reading_progress_bar_settings_page_html']
        );
    }

    /**
     * Render Settings Page HTML
     *
     * Outputs the mount point for the React settings interface.
     * The React application (compiled via @wordpress/scripts) detects the
     * #reading-progress-bar-settings element and renders the full settings UI
     * into it. The fallback text is shown only while the script is loading.
     *
     * @since 1.0.0
     */
    public function reading_progress_bar_settings_page_html()
    {
        printf(
            '<div class="wrap" id="reading-progress-bar-settings">%s</div>',
            esc_html__('Loading…', 'reading-progress-bar')
        );
    }

    /**
     * Enqueue Settings Page Scripts
     *
     * Loads the compiled React bundle only on the plugin settings page
     * (settings_page_reading-progress-bar). The asset manifest generated by
     * @wordpress/scripts is used to declare correct dependencies and cache-bust
     * the script version automatically on each build.
     *
     * @since 1.0.0
     * @param string $admin_page The current admin page slug passed by admin_enqueue_scripts.
     */
    public function reading_progress_bar_settings_page_enqueue_script($admin_page)
    {
        // Bail early if we are not on this plugin's settings page.
        if ('settings_page_reading-progress-bar' !== $admin_page) {
            return;
        }

        // The asset file is generated by `wp-scripts build` and contains the
        // dependency array and a content-hash version string.
        $asset_file = plugin_dir_path(__FILE__) . 'build/index.asset.php';

        if (! file_exists($asset_file)) {
            return;
        }

        $asset = include $asset_file;

        wp_enqueue_script(
            'reading-progress-bar-script',
            plugins_url('build/index.js', __FILE__),
            $asset['dependencies'],
            $asset['version'],
            array(
                'in_footer' => true,
            )
        );
    }

    /**
     * Enqueue Frontend Style
     *
     * Loads the compiled CSS on every frontend page. The stylesheet contains
     * the CSS Scroll Timeline animation that drives the progress bar — it must
     * be present even before the bar <div> is rendered so the animation fires
     * correctly. No script dependencies are needed for the frontend style.
     *
     * @since 1.0.0
     */
    public function reading_progress_bar_enqueue_style()
    {
        // Reuse the asset manifest produced by `wp-scripts build` for the
        // version hash; no JS dependencies apply to the stylesheet.
        $asset_file = plugin_dir_path(__FILE__) . 'build/index.asset.php';

        if (! file_exists($asset_file)) {
            return;
        }

        $asset = include $asset_file;

        // Firefox pollyfill not working need to look into the future relase
        wp_enqueue_script(
            'scroll-timeline-polyfill',
            plugins_url('src/polyfill-scroll-timeline.js', __FILE__),
            $asset['dependencies'],
            $asset['version'],
            array(
                'in_footer' => false,
            )
        );

        wp_enqueue_style(
            'reading-progress-bar-style',
            plugins_url('build/index.css', __FILE__),
            array(),
            $asset['version'],
        );
    }

    /**
     * Register Plugin Settings
     *
     * Registers the `reading_progress_bar` option in the WordPress options table
     * and exposes it via the REST API (/wp/v2/settings). The React settings page
     * reads and writes this option exclusively through the REST API, so both the
     * `show_in_rest` schema and the `sanitize_callback` are required.
     *
     * @since 1.0.0
     */
    public function reading_progress_bar_settings()
    {
        // Factory defaults applied when the option does not yet exist in the DB.
        $default = array(
            'height'           => 8,
            'posttype'         => array('post'),
            'color'            => '#000000',
            'foreground_color' => '#000000',
            'position'         => 'top',
            'adjust_position'  => 30,
        );

        // JSON Schema used by the REST API to validate incoming values before
        // they reach the sanitize_callback. The `enum` on `position` restricts
        // the value to 'top' or 'bottom' at the API layer.
        $schema = array(
            'type'       => 'object',
            'properties' => array(
                'height' => array(
                    'type'    => 'integer',
                    'minimum' => 0,
                    'maximum' => 100,
                ),
                'posttype' => array(
                    'type'              => 'array',
                    'sanitize_callback' => 'sanitize_key',
                ),
                'color' => array(
                    'type'              => 'string',
                    'sanitize_callback' => 'sanitize_hex_color',
                ),
                'foreground_color' => array(
                    'type'              => 'string',
                    'sanitize_callback' => 'sanitize_hex_color',
                ),
                'position' => array(
                    'type' => 'string',
                    'enum' => array('top', 'bottom'),
                ),
                'adjust_position' => array(
                    'type'    => 'integer',
                    'minimum' => 0,
                    'maximum' => 100,
                ),
            ),
        );

        register_setting(
            'options',
            'reading_progress_bar',
            array(
                'type'              => 'object',
                'default'           => $default,
                'sanitize_callback' => [$this, 'reading_progress_bar_sanitize'],
                'show_in_rest'      => array(
                    'schema' => $schema,
                ),
            )
        );
    }

    /**
     * Sanitize Settings
     *
     * Sanitizes each setting field before saving to the database.
     *
     * @since 1.0.0
     * @param mixed $value The raw settings value.
     * @return array Sanitized settings.
     */
    public function reading_progress_bar_sanitize($value)
    {
        if (! \is_array($value)) {
            return array();
        }

        $sanitized = array();

        if (isset($value['height'])) {
            $sanitized['height'] = \absint($value['height']);
        }

        if (isset($value['posttype'])) {
            // Handle posttype as an array of post type slugs
            if (\is_array($value['posttype'])) {
                $sanitized['posttype'] = \array_map('sanitize_key', $value['posttype']);
            } else {
                // Support legacy single-value format for backwards compatibility
                $sanitized['posttype'] = array(\sanitize_key($value['posttype']));
            }
        }

        if (isset($value['color'])) {
            $sanitized['color'] = \sanitize_hex_color($value['color']);
        }

        if (isset($value['foreground_color'])) {
            $sanitized['foreground_color'] = \sanitize_hex_color($value['foreground_color']);
        }

        if (isset($value['position'])) {
            $sanitized['position'] = \in_array($value['position'], array('top', 'bottom'), true)
                ? $value['position']
                : 'top';
        }

        if (isset($value['adjust_position'])) {
            $sanitized['adjust_position'] = \absint($value['adjust_position']);
        }

        return $sanitized;
    }

    /**
     * Render Frontend Progress Bar
     *
     * Outputs the #progress <div> immediately after <body> opens on singular
     * posts matching the configured post type. All visual properties (color,
     * foreground color, height, and top/bottom position offset) are compiled
     * into an inline style using WP_Style_Engine so the output is minimal and
     * consistent with the block editor's style pipeline.
     *
     * The actual scroll animation is driven entirely by the CSS Scroll Timeline
     * API defined in src/index.scss — no JavaScript is required at runtime.
     *
     * @since 1.0.0
     */
    public function reading_progress_bar_front_page()
    {
        $options = \get_option('reading_progress_bar');

        // Do nothing if no post types have been configured yet.
        if (! isset($options['posttype']) || empty($options['posttype'])) {
            return;
        }

        // Ensure posttype is an array (for backwards compatibility)
        $post_types = \is_array($options['posttype']) ? $options['posttype'] : array($options['posttype']);

        // Only render on single posts/pages that match one of the selected post types.
        if (\is_singular() && \in_array(\get_post_type(), $post_types, true)) {
            // Re-sanitize each value as a defence-in-depth measure in case the
            // stored option was written directly (bypassing the REST sanitize_callback).
            $height          = isset($options['height']) ? \absint($options['height']) : 8;
            $color           = isset($options['color']) ? \sanitize_hex_color($options['color']) : '#000000';
            $foreground      = isset($options['foreground_color']) ? \sanitize_hex_color($options['foreground_color']) : '#000000';
            $position        = isset($options['position']) && 'bottom' === $options['position'] ? 'bottom' : 'top';
            $adjust_position = isset($options['adjust_position']) ? \absint($options['adjust_position']) : 0;

            // Compile a minimal inline style string.  The dynamic $position key
            // resolves to either 'top' or 'bottom' based on the saved setting.
            $css = \WP_Style_Engine::compile_css(
                array(
                    'background' => $color,
                    'color'      => $foreground,
                    'height'     => $height . 'px',
                    $position    => $adjust_position . 'px',
                ),
                ''
            );

            \printf(
                '<div id="progress" style="%s"></div>',
                \esc_attr($css)
            );
        }
    }

    public function delete_reading_progress_bar_option()
    {
        delete_option('reading_progress_bar');
    }
}

// Initialize the plugin
new Reading_Progress_Bar();
